spring.application.name=nurse-shifts

# H2 Database connection
spring.datasource.url=jdbc:h2:file:./nurse_shifts
spring.datasource.driver-class-name=org.h2.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true
